### ISSUE TITLE
Tag log failure after log complete

### ISSUE THREAD

**Issue by ConnerHAnderson** [ConnerHAnderson/discord-hvz#23]
```
Traceback (most recent call last):
  File "C:\Users\conne\Dev\discord-hvz\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\conne\Dev\discord-hvz\discord-hvz.py", line 126, in on_message
    await resolve_chat(chatbot)
  File "C:\Users\conne\Dev\discord-hvz\discord-hvz.py", line 310, in resolve_chat
    tagged_user_id = int(tagged_member_data['id'])
KeyError: 'id'
```

**Comment by ConnerHAnderson** [comment]
Never found the bug.
